parameters:
  loss_weights:
    mae: 1.0
    w_mass_mmd0: 2.5
    w_mass_mmd1: 2.5
    higgs_mass: 1.0
    alpha: 0.0 # TODO: study this hyperparameter
  batch_size: 256
  epochs: 1024
  learning_rate: 1.0e-5
  attn_dim: 256
  num_head: 16
  num_self_attn: 5
  num_cross_attn: 5

paths:
  project_name: "hww_pctransformer_kfold"
  saved_path: "/root/work/hww_pctransformer/hww_pctransformer_kfold"
  data_path: "/root/data/danning_h5/ypeng/mc20_qe_v4_recotruth_merged.h5"

seed: 114
